# Example in https://dzone.com/articles/using-yaml-java-application

version: 1.1.x
released: 2020-02-12

# Logging Configuration
loggerConfig:
  fileName: mqttGateway.log
  maxFileSize: 100000
  maxNumberOfFiles: 10
  appendFiles: true
  debugLevel: ALL

# MQTT Broker Config
broker:
  # For Dev
  host: 127.0.0.1
  port: 9883
  # For Production
  # host: ea-pc165.ei.htwg-konstanz.de
  # port: 1883
  # From docker container
  # host:
  # port: 8883

database:
  host: 127.0.0.1
  port: 8086
  username: aut_labor
  password: secret
  name: aut_labor_db


# TTN Applications and the corresponding API Keys
applications:
  test-user-app: some-api-key-214335009
  test-user-app2: some-api-key-769238943

# MQTT Topics regex
regex: v3/(?<app>.*?)/devices/(?<device>.*?)/(?:(?<type>[\w&&[^/]]*)/?(?<downType>.*?)?)

# For List use
#List:
#  - element1
#  - element2
