# This file is part of the Stack Deployment of the HTWG IoT Infrastructur Solution
# Author: Mouaad Gssair, M.Gssair@htwg-konstanz.de
# This Yaml file  is the docker compose file for deploying Portainer to monitor the docker containers 
# of the HTWG IoT Infrastructur Solution

# Refer to this Link for other options of deploying Portainer
# https://portainer.readthedocs.io/en/latest/deployment.html

version: '3'

services:
  portainer:
    image: portainer/portainer
    command: -H unix:///var/run/docker.sock
    restart: always
    ports:
      - 9000:9000
      - 8000:8000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data

volumes:
  portainer_data: