# When Using DNS
#oauth-server-address: 'http://wireless-iot-pc.aut.ei.htwg-konstanz.de/oauth'

#identity-server-grpc-address: 'wireless-iot-pc.aut.ei.htwg-konstanz.de:8884'
#gateway-server-grpc-address: 'wireless-iot-pc.aut.ei.htwg-konstanz.de:8884'
#network-server-grpc-address: 'wireless-iot-pc.aut.ei.htwg-konstanz.de:8884'
#application-server-grpc-address: 'wireless-iot-pc.aut.ei.htwg-konstanz.de:8884'
#join-server-grpc-address: 'wireless-iot-pc.aut.ei.htwg-konstanz.de:8884'
#device-template-converter-grpc-address: 'wireless-iot-pc.aut.ei.htwg-konstanz.de:8884'

# Without DNS
oauth-server-address: 'https://localhost:8885/oauth'

identity-server-grpc-address: 'localhost:8884'
gateway-server-grpc-address: 'localhost:8884'
network-server-grpc-address: 'localhost:8884'
application-server-grpc-address: 'localhost:8884'
join-server-grpc-address: 'localhost:8884'
device-template-converter-grpc-address: 'localhost:8884'