name: Java CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - run: mkdir -p src/Services/Plant-Browser/plant-browser-release
    
    - name: Clean with Maven
      run: mvn clean --file src/Services/Plant-Browser/pom.xml
    - name: Build with Maven
      run: mvn -B package --file src/Services/Plant-Browser/pom.xml
    - uses: actions/upload-artifact@master
      with:
        name: plant-browser-service.jar
        path: src/Services/Plant-Browser/plant-browser-release